### ISSUE TITLE
Import error for "rcl_helpers" when running after pip install.

### ISSUE THREAD

**Issue by Ben-Ryder** [Ben-Ryder/rcl#2]
**Describe the bug**
The application is crashing with:
```
Traceback (most recent call last):
  File "/Users/<user>/Library/Python/3.7/bin/rcl", line 6, in <module>
    from rcl import cli
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/rcl.py", line 5, in <module>
    import rcl_helpers
ModuleNotFoundError: No module named 'rcl_helpers'
```
This is occurring on a fresh install using pip. It is possibly due to a packaging problem or where the script is being saved. Some investigation is needed. I will also check documentation on packaging [Click](https://click.palletsprojects.com/en/7.x/) projects & python projects in general.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install using pip.
2. Try to run the `rcl` command. (ran from ~)

**Expected behaviour**
It works...

**System Information (please complete the following information):**
 - OS: Mac - Catalina 10.15.6
 - Python Version: 3.7.3

**Additional context**
n/a

**Comment by Ben-Ryder** [comment]
So far this is not reproducible on Ubuntu 18.04, although this is the system I have used to develop `rcl` so it is potentially not a clean install.

**Comment by Ben-Ryder** [comment]
I can now confirm a similar error is reproducible for a fresh Ubuntu 18.04 installation. `pip install rcl` gives a warning:;
```
WARNING: The script rcl is installed in '/home/ubuntu/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
And on trying to run `rcl` it is not found. This warning was also seen on the mac but detailing a different install location.
This is issue looks to indeed be related to how/where the application is installed.

**Comment by Ben-Ryder** [comment]
After ensuring a clean uninstall, I can now reproduce this on my main system.

Running the program in venv for development as per [Click's documentation](https://click.palletsprojects.com/en/7.x/setuptools/#testing-the-script) does still work fine. Installing via pip gives the original error in the issue:
```
Traceback (most recent call last):
  File "/home/<user>/.local/bin/rcl", line 7, in <module>
    from rcl import cli
  File "/home/<user>/.local/lib/python2.7/site-packages/rcl.py", line 5, in <module>
    import rcl_helpers
ImportError: No module named rcl_helpers
```
I am going to try to fix this by making the script be contained within a python package as per the [docs](https://click.palletsprojects.com/en/7.x/setuptools/#scripts-in-packages).

**Comment by Ben-Ryder** [comment]
Opened PR #6 to look to solve this. As said on that PR:

> Fixing the error `ModuleNotFoundError: No module named 'rcl_helpers'` being thrown by a cleanly installed rcl by converting the program to use a python package.
> 
> This has been tested using [Test PyPI](https://test.pypi.org/project/rcl/) (`pip install -i https://test.pypi.org/simple/ rcl`) on my Ubuntu 18.04 environment, a new live-booted Ubuntu 18.04 and a Mac with Catalina 10.15.6 and it looks to work fine.
> It still cause the warning about the install location not being on `$PATH` but this is a separate issue, if it is one.

**Comment by ben-ryder** [comment]
#6 fixes this issue. Tested on Ubuntu and Mac with `pip install rcl --no-cache-dir`.

A new version [v0.1.2](https://github.com/Ben-Ryder/rcl/releases/tag/v0.1.2) has been released to publish this fix which also closes #1 and completes the [Stable MVP Release Milestone](https://github.com/Ben-Ryder/rcl/milestone/1).

**Comment by ben-ryder** [comment]
I still have a similar error on Ubuntu 18.04 on a complete fresh OS:
```
Traceback (most recent call last):
  File "/home/ben/.local/bin/rcl", line 7, in <module>
    from rcl.main import cli
  File "/home/ben/.local/lib/python3.6/site-packages/rcl/main.py", line 5, in <module>
    import helpers
ModuleNotFoundError: No module named 'helpers'
```

I managed to fix the issue by editing the import in `main.py` 
```python
import helpers
```
becomes:
```python
import rcl.helpers as helpers
```

**Comment by ben-ryder** [comment]
This issue (and fix to change the import to `import rcl.helpers as helpers`) also works on MacOS.
